[general]
import = [
#"~/.config/alacritty/colors/tui.toml",
"~/.config/alacritty/colors/catppuccin-mocha.toml",
]

[window]
padding = { x = 20, y = 20 }

[scrolling]
history = 5000

[cursor]
style = { blinking = "Always" }
thickness = 0.2

[terminal]
shell = "fish"
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", mods = "Control", action = "Copy" },
    { mouse = "Right", action = "Paste" },
]

[font]
normal = { family = "GeistMono NF" }
bold = { family = "GeistMono NF" }
italic = { family = "GeistMono NF" }
bold_italic = { family = "GeistMono NF" }
size = 9.5
