[colors]
# Paleta brillante estilo retro-terminal (inspirada en la imagen)

[colors.primary]
background = "0x000000"  # negro puro
foreground = "0xffffff"  # blanco puro

[colors.normal]
black   = "0x000000"
red     = "0xff5f5f"  # rojo brillante
green   = "0x5fff5f"  # verde neón
yellow  = "0xffff5f"  # amarillo fuerte
blue    = "0x5f87ff"  # azul claro
magenta = "0xff5fff"  # fucsia vivo
cyan    = "0x5fffff"  # cian eléctrico
white   = "0xe5e5e5"

[colors.bright]
black   = "0x4c4c4c"   # gris medio
red     = "0xff8787"
green   = "0x87ff87"
yellow  = "0xffff87"
blue    = "0x87afff"
magenta = "0xff87ff"
cyan    = "0x87ffff"
white   = "0xffffff"
