[opener]
edit = [
    { run = 'for a in "$@"; do if [ -d "$a" ]; then code "$a"; else micro "$a"; fi; done', desc = "smart edit", block = true },
	{ run = '${EDITOR:-micro} "$@"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code %*',    orphan = true, desc = "code",           for = "windows" },
	{ run = 'code -w %*', block = true,  desc = "code (block)",   for = "windows" },
]

[mgr]
show_hidden = true
